version: '2'
services:

  dev:
    build: build/node
    image: dev:latest
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src

  browser:
    build: build/bsync
    image: bsync:latest
    volumes:
      - ./dist:/app/dist
    ports:
      - "3000:3000"
    depends_on:
      - dev
