version: '2'
services:

  ui:
    image: c4tech/node
    volumes:
      - .:/app

  browsersync:
    command: browser-sync start --config bs-config.js
    image: ulsmith/browsersync
    volumes:
      - .:/app
    ports:
      - "${PORT:-3000}:3000"
    labels:
      - "traefik.backend=ui"
      - "traefik.frontend.rule=Host:ui.docker.localhost"

networks:
  default:
    external:
      name: docker_docker-localhost
